name: mypantry
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0-75.1.beta

dependencies:
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  http: ^1.5.0
  riverpod: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
